apiVersion: v1
kind: Pod
metadata:
  name: haproxy
  namespace: kube-system
  labels:
    tier: control-plane
    component: load-balancer
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
spec:
  hostNetwork: true
  containers:
  - name: haproxy
    image: telephoneorg/kubeapi-lb
    imagePullPolicy: IfNotPresent
    env:
    - name: CLUSTER_LOCAL_DNS
      value: cluster.local.valuphone.com
    ports:
    - containerPort: 6443
      hostPort: 6443
    resources:
      requests:
        cpu: 500m
